### PR TITLE
Move embarkjs

### PR DESCRIPTION
**Pull request by michaelsbradleyjr**
Initial work to extract `embark.js` from Embark and have it be a separate npm package.

`package.json` needs a bit more work prior to publishing to the npm registry; README needs to be filled in, and we may want to think about packaging `embark.min.js` in GitHub releases.

-------

If you clone this branch and run `npm install . && npm build`, scripts in `src/` will be run through babel and output in `dist/`. Also, the browser entrypoint will be run through webpack and an `embark.min.js` file will be output in the project root.

# Rationale

`src/embark.js` is written as an ES module, e.g. making use of `export default` and could possibly make use of `import` or other JS lang features that babel supports via polyfill.

In order to have that script be a proper node module, consumable via `require()` by other modules, such as Embark itself, `/src/embark.js` is run through babel. It is not necessary that it be run through webpack, only that it be a valid commonjs module. A `dist/index.js` entrypoint is provided for node (see `"main"` in `package.json`) to get around the `exports.default` issue when babel compiles ES modules to commonjs.

A different entrypoint, `dist/browser.js` is provided (see `"browser"` in `package.json`), which will be respected by downstream webpack pipelines (e.g. Embark's pipeline) and other pipeline-tools that know to look for it — `"browser"` field in `package.json` is a standard thing.

The browser entrypoint is used by `webpack.config.js` to generate a suitable standalone `embark.min.js` that someone could plop into a `<script>` tag, if they wanted to use EmbarkJS in that way.

I did one thing experimentally, which also shows the utility of having a separate browser entrypoint. That is, I split out part of the testing for `this.web3` so that global/window detection only ends up in the code that's built by webpack when it goes through the browser entrypoint.  If that's not desirable, I can get rid of it and then change the browser entrypoint  to `dist/embark.js`.

### CODE REVIEW

**Review by jrainville — APPROVED** [review]
Looks good. For when we publish to npm for us/users to use, should we already have the dist published?

**Comment by michaelsbradleyjr** [comment]
just rebased to clean up the commit history

**Comment by michaelsbradleyjr** [comment]
@jrainville the scripts in `dist/` as well as `embark.min.js` will get packed by npm, provided that `npm run build` has been run prior to publishing the package. `package.json` supports some publishing related scripts, will take a look at that shortly.

It might be nice to include `embark.min.js` and the scripts in `dist/` in a GitHub release, as they're ignored by `.gitignore`. Not sure how to do that, but I imagine there's some npm package to make it easy.

**Comment by michaelsbradleyjr** [comment]
I specified a `"prepack"` script per https://docs.npmjs.com/misc/scripts

**Comment by michaelsbradleyjr** [comment]
Improved babel and webpack configurations, the result being *much* smaller builds of `embark.min.js`.

I tested using webpack in an external module which imports EmbarkJS (made available to it via `npm link`) and the changed `"browser"` field in `package.json`, which now points to `src/browser.js` vs. `dist/browser.js`, is respected and it works fine, i.e. even though `src/browser.js` hasn't already been passed through webpack and/or babel.

**Comment by michaelsbradleyjr** [comment]
Might be too much trouble to implement at present, but this tool could be useful:

https://www.npmjs.com/package/github-release-cli

The idea would be to have a `"postpublish"` script that invokes `github-release`. An archive of the repo (including artifacts of `npm build`) and `embark.min.js` could be included as files in the release. The archive would already contain `embark.min.js`, but it might be convenient to developers (who want to use the standalone build) to be able to download it directly from a release's page on GitHub.

The person responsible for running `npm publish` would need to have `$GITHUB_TOKEN` in his shell environment and the `postpublish` script would make use of that.

**Comment by michaelsbradleyjr** [comment]
added description to `package.json`; added same to README, with a link to Embark on GitHub.

I think we're good to go for an initial tag and package version.

Running `npm publish` will automatically run `npm run build` per the `"prepack"` script.

**Review by iurimatias — APPROVED** [review]

**Pull request merged**
